version: '3.9'

services:
  carpediem:
    build: .
    container_name: carpediem
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - carpediem_data:/carpediem_data
    restart: always

volumes:
  carpediem_data:
    driver: local
