services:
  carpediem:
    build: .
    container_name: carpediem
    ports:
      - "${PORT:-8001}:8001"
    env_file:
      - .env
    volumes:
      - carpediem_data:/carpediem_data
    restart: always

  carpediem_imgs:
    driver: instance/imgmaple
  carpediem_data:
    driver: local
