services:
  carpediem:
    build: .
    container_name: carpediem
    ports:
      - "${PORT:-8001}:8001"
    env_file:
      - .env
    volumes:
      - carpediem_data:/carpediem_data
      - carpediem_imgs:/app/static/imgmaple
    restart: always

volumes:
  carpediem_data:
    driver: local
